language: python
python:
  - "3.9"  # 3.9 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
# command to run tests
script:
  - coverage run -m unittest discover -s . -p 'test_*.py'