language: python
python:
  - "3.9"  # 3.9 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
# command to run tests
script:
  - coverage run -m unittest discover

after_success:
  - coveralls

deploy:
  provider: heroku
  api_key:
    secure: 8ab8e42a-121d-4362-94c5-84b846fec0b9