"""Initial migration.

Revision ID: 768825423482
Revises: 
Create Date: 2022-01-09 17:58:41.214264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768825423482'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.create_table('reservation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('master_id', sa.INTEGER(), nullable=True),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('breed_id', sa.INTEGER(), nullable=True),
    sa.Column('procedure_id', sa.INTEGER(), nullable=True),
    sa.Column('time_from', sa.TIME(), nullable=False),
    sa.Column('time_to', sa.TIME(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('final_price', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['breed_id'], ['breed.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    col = sa.Column('procedure_reservations', sa.INTEGER())
    col.create('procedure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_time_slot',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('master_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('starting_hour', sa.TIME(), nullable=True),
    sa.Column('ending_hour', sa.TIME(), nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedure',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('basic_price', sa.INTEGER(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('breed',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('fur_coefficient', sa.FLOAT(), nullable=True),
    sa.Column('size_coefficient', sa.FLOAT(), nullable=True),
    sa.Column('image_link', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reservation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('master_id', sa.INTEGER(), nullable=True),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('breed_id', sa.INTEGER(), nullable=True),
    sa.Column('procedure_id', sa.INTEGER(), nullable=True),
    sa.Column('time_from', sa.TIME(), nullable=False),
    sa.Column('time_to', sa.TIME(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('final_price', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['breed_id'], ['breed.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_procedure',
    sa.Column('master_id', sa.INTEGER(), nullable=False),
    sa.Column('procedure_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], ),
    sa.PrimaryKeyConstraint('master_id', 'procedure_id')
    )
    op.create_table('master',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('stars', sa.INTEGER(), nullable=True),
    sa.Column('number_of_marks', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=80), nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_phone', 'user', ['phone'], unique=False)
    # ### end Alembic commands ###
